function A_Obj_2f = A_Obj_2f(T,k_theta,k_xi,lambda_xi,lambda_theta,rho,sig_xi,sig_theta,theta_bar)
%A_Obj_2f
%    A_Obj_2f = A_Obj_2f(T,K_THETA,K_XI,LAMBDA_XI,LAMBDA_THETA,RHO,SIG_XI,SIG_THETA,THETA_BAR)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-Jul-2024 16:25:16

t2 = conj(lambda_xi);
t3 = conj(lambda_theta);
t4 = T.*k_theta;
t5 = T.*k_xi;
t6 = rho.^2;
t7 = -k_xi;
t8 = 1.0./k_theta;
t9 = -t4;
t10 = -t5;
t11 = -t6;
t14 = k_theta+t7;
t12 = exp(t9);
t13 = exp(t10);
t15 = t11+1.0;
t18 = 1.0./t14;
t16 = t12-1.0;
t17 = t13-1.0;
t19 = sqrt(t15);
t20 = conj(t19);
A_Obj_2f = [-k_theta.*t17.*t18.*theta_bar+k_xi.*t16.*t18.*theta_bar-(sig_xi.*t2.*t17)./k_xi-rho.*sig_theta.*t2.*t17.*t18-sig_theta.*t3.*t17.*t18.*t20+k_xi.*rho.*sig_theta.*t2.*t8.*t16.*t18+k_xi.*sig_theta.*t3.*t8.*t16.*t18.*t20;-t16.*theta_bar-rho.*sig_theta.*t2.*t8.*t16-sig_theta.*t3.*t8.*t16.*t20];
end
