function V_Obj_2f = V_Obj_2f(T,k_theta,k_xi,rho,sig_xi,sig_theta)
%V_Obj_2f
%    V_Obj_2f = V_Obj_2f(T,K_THETA,K_XI,RHO,SIG_XI,SIG_THETA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    27-Jul-2024 16:25:17

t2 = T.*k_theta;
t3 = T.*k_xi;
t4 = k_theta+k_xi;
t5 = k_xi.^2;
t6 = sig_theta.^2;
t9 = -k_xi;
t10 = 1.0./k_theta;
t7 = t2.*2.0;
t8 = t3.*2.0;
t11 = -t2;
t13 = -t3;
t17 = k_theta+t9;
t18 = 1.0./t4;
t12 = -t7;
t14 = -t8;
t21 = 1.0./t17;
t23 = t11+t13;
t15 = exp(t12);
t16 = exp(t14);
t22 = t21.^2;
t24 = exp(t23);
t19 = t15-1.0;
t20 = t16-1.0;
t25 = t24-1.0;
t26 = rho.*sig_xi.*sig_theta.*t18.*t25;
t28 = (k_xi.*t6.*t10.*t19.*t21)./2.0;
t30 = t6.*t9.*t18.*t21.*t25;
t27 = -t26;
t31 = t27+t28+t30;
V_Obj_2f = reshape([(sig_xi.^2.*t20.*(-1.0./2.0))./k_xi+k_xi.*t21.*t26.*2.0-(k_xi.*t6.*t20.*t22)./2.0-rho.*sig_xi.*sig_theta.*t20.*t21-(t5.*t6.*t10.*t19.*t22)./2.0+t5.*t6.*t18.*t22.*t25.*2.0,t31,t31,t6.*t10.*t19.*(-1.0./2.0)],[2,2]);
end
